version: "3.1"

services:
  build-tester:
    image: ianwalter/puppeteer:3.0.2
    entrypoint:
      - /bin/sh
      - ./dockerEntry.sh
    volumes:
      - $PWD:/opt/codec
    working_dir: /opt/codec
